export default [
  {
    files: ['**/*.js'],
    ignores: ['node_modules/**', 'logs/**', 'dist/**'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
    },
    rules: {
      eqeqeq: ['error', 'always'],
      'no-throw-literal': 'error',
      'require-await': 'error',
      'no-return-await': 'error',
      'consistent-return': 'error',
      'no-empty': ['error', { allowEmptyCatch: false }],
      'no-var': 'error',
      'prefer-const': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-shadow': 'error',
      'no-param-reassign': 'error',
      'max-params': ['error', 4],
      'max-lines-per-function': ['warn', { max: 40, skipBlankLines: true, skipComments: true }],
      'arrow-body-style': ['error', 'as-needed'],
      'max-depth': ['error', 3],
      'max-lines': ['warn', { max: 250, skipBlankLines: true, skipComments: true }],
      'no-console': 'warn',
      'no-process-exit': 'error',
      'no-multiple-empty-lines': ['error', { max: 1, maxEOF: 0 }],
      curly: ['error', 'all'],
      'no-multi-spaces': 'error',
      indent: ['error', 2, { SwitchCase: 1 }],
      'max-len': ['error', {
        code: 200,
        ignoreUrls: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreRegExpLiterals: true,
      }],
      'block-spacing': ['error', 'always'],
      'object-curly-spacing': ['error', 'always'],
      'comma-spacing': ['error', { before: false, after: true }],
      'space-before-blocks': ['error', 'always'],
      'key-spacing': ['error', { beforeColon: false, afterColon: true }],
      'space-infix-ops': 'error',
    },
  },
  {
    // Тесты: моки возвращают промисы без await, describe-блоки длинные,
    // файлы крупные — эти стилевые правила к тестам не применяем.
    files: ['tests/**/*.js'],
    rules: {
      'require-await': 'off',
      'max-lines-per-function': 'off',
      'max-lines': 'off',
      'no-console': 'off',
    },
  },
];
